import * as THREE from 'three';
import './style.css';
const $=i=>document.getElementById(i),V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const U={boot:$('boot'),menu:$('menu'),game:$('game-ui'),fill:$('boot-progress-fill'),bt:$('boot-text'),obj:$('objective'),prompt:$('prompt'),hp:$('hp-value'),suit:$('suit-value'),sector:$('sector-value'),weapon:$('weapon-name'),ammo:$('ammo-value'),hit:$('hitmarker'),damage:$('damage-flash'),pause:$('pause-overlay'),end:$('end-overlay'),mobile:$('mobile-controls')};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x04090d);scene.fog=new THREE.FogExp2(0x081117,.024);const cam=new THREE.PerspectiveCamera(76,innerWidth/innerHeight,.05,140);
const r=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});r.setPixelRatio(Math.min(devicePixelRatio,1.5));r.setSize(innerWidth,innerHeight);r.shadowMap.enabled=true;r.outputColorSpace=THREE.SRGBColorSpace;
scene.add(new THREE.HemisphereLight(0x9ab9c8,0x081014,.62));const sun=new THREE.DirectionalLight(0xaad8e8,.7);sun.position.set(-14,22,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);const alarm=new THREE.PointLight(0x66151d,2.2,16);alarm.position.set(0,3,-14);scene.add(alarm);const lamp=new THREE.PointLight(0xcdefff,.8,7);scene.add(lamp);
const M={wall:new THREE.MeshStandardMaterial({color:0x35454b,roughness:.88}),wall2:new THREE.MeshStandardMaterial({color:0x59686c,roughness:.82}),floor:new THREE.MeshStandardMaterial({color:0x28363a,roughness:1}),dark:new THREE.MeshStandardMaterial({color:0x121c20,roughness:.96}),metal:new THREE.MeshStandardMaterial({color:0x74868a,roughness:.48,metalness:.7}),glass:new THREE.MeshStandardMaterial({color:0x2b8fab,roughness:.12,metalness:.25,transparent:true,opacity:.42}),alien:new THREE.MeshStandardMaterial({color:0x5e7a55,roughness:.95}),alien2:new THREE.MeshStandardMaterial({color:0x23352a,roughness:.9}),white:new THREE.MeshStandardMaterial({color:0xb9c2c1,roughness:.55})};
const W=new THREE.Group();scene.add(W),solids=[],foes=[],drops=[],fx=[];let doorOpen=false,state='boot',now=0;
const P={p:V(0,1.72,18),v:V(),yaw:Math.PI,pitch:0,r:.32,ground:true,hp:100,suit:100,slot:0,mag:[12,4],res:[48,20],cd:0,reload:0,stage:0,stageTime:0};
const guns=[{name:'SIDEARM',max:12,rate:.16,dmg:24,range:42},{name:'PULSE CARBINE',max:4,rate:.48,dmg:48,range:32}],keys=new Set(),mouse={lock:false,dx:0,dy:0},touch={l:{x:0,y:0,on:false},rr:{x:0,y:0,on:false},jump:false};
const audio={ctx:null,beep(f,d,t='sine',g=.03){try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();this.ctx.resume();let o=this.ctx.createOscillator(),a=this.ctx.createGain();o.type=t;o.frequency.value=f;a.gain.setValueAtTime(.001,this.ctx.currentTime);a.gain.exponentialRampToValueAtTime(g,this.ctx.currentTime+.006);a.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+d);o.connect(a).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+d+.02)}catch{}}};
function box(x,y,z,a,b,c,m=M.wall,cast=false){let q=new THREE.Mesh(new THREE.BoxGeometry(a,b,c),m);q.position.set(x,y,z);q.castShadow=cast;q.receiveShadow=true;W.add(q);return q} function wall(x,z,a,c,door=false){solids.push({x,z,a:a/2,c:c/2,door})}
function room(z,w,d,h=5){box(0,0,z,w,.2,d,M.floor);box(0,h,z,w,.2,d,M.dark);box(-w/2,h/2,z,.3,h,d);box(w/2,h/2,z,.3,h,d);box(0,h/2,z-d/2,w,h,.3);box(0,h/2,z+d/2,w,h,.3);wall(-w/2,z,.3,d);wall(w/2,z,.3,d);wall(0,z-d/2,w,.3);wall(0,z+d/2,w,.3)}
function cor(z,w=8,d=10){box(0,0,z,w,.2,d,M.floor);box(0,5,z,w,.2,d,M.dark);box(-w/2,2.5,z,.3,5,d,M.wall2);box(w/2,2.5,z,.3,5,d,M.wall2);wall(-w/2,z,.3,d);wall(w/2,z,.3,d)}
function lum(z,c=0x7adff2){let l=new THREE.PointLight(c,2.5,8);l.position.set(-4.2,4.1,z);W.add(l);box(-4.2,4.1,z,1.6,.04,.08,new THREE.MeshBasicMaterial({color:c}))}
function foe(type,x,z){let g=new THREE.Group();g.position.set(x,.8,z);let b=new THREE.Mesh(new THREE.SphereGeometry(type==='spitter'?.58:.48,10,8),type==='spitter'?M.alien:M.alien2);b.scale.y=1.25;b.castShadow=true;g.add(b);let e=new THREE.Mesh(new THREE.SphereGeometry(.16,8,6),new THREE.MeshBasicMaterial({color:type==='spitter'?0xffc36c:0xff4f5d}));e.position.set(0,.38,-.36);g.add(e);W.add(g);foes.push({g,type,hp:type==='spitter'?70:44,cool:Math.random(),speed:type==='spitter'?1.7:2.1,phase:Math.random()*5,dead:false})}
function drop(type,x,z){let g=new THREE.Group();g.position.set(x,.72,z);g.add(new THREE.Mesh(type==='med'?new THREE.BoxGeometry(.42,.24,.72):new THREE.CylinderGeometry(.18,.18,.6,8),type==='med'?M.white:M.metal));g.add(new THREE.PointLight(type==='med'?0x65ff8c:0xffbd62,1.2,3));W.add(g);drops.push({g,type,used:false})}
function build(){W.clear();solids.length=foes.length=drops.length=fx.length=0;room(16,12,16);cor(3);room(-7,14,10);cor(-17);room(-28,18,12,5.5);cor(-39,10);room(-50,22,16,6);[-20,-13,-3,13,20,-31,-46,-54].forEach(lum);box(0,1.3,8,2.8,1.4,.7,M.metal,true);box(0,2.5,-28,3.5,4.7,1.6,M.glass,true);box(0,2.1,-16,4.5,4,.35,M.metal,true);wall(0,-16,4.8,.8,true);drop('med',-2,14);drop('ammo',3,10);drop('ammo',-4,-6);drop('med',4,-30);drop('ammo',-5,-52);foe('runner',-3.6,-4);foe('runner',3.6,-7);foe('spitter',0,-12);foe('runner',-5,-31);foe('runner',5,-34);foe('spitter',0,-47);foe('runner',-5,-51);foe('runner',5,-53)}
function reset(){Object.assign(P,{p:V(0,1.72,18),v:V(),yaw:Math.PI,pitch:0,ground:true,hp:100,suit:100,slot:0,mag:[12,4],res:[48,20],cd:0,reload:0,stage:0,stageTime:0});doorOpen=false;state='playing';build();cam.position.copy(P.p);obj('Activate the initialization console.')}
function obj(t){U.obj.textContent=t} function hurt(n){let absorb=Math.min(P.suit,Math.floor(n*.35));P.suit-=absorb;P.hp-=n-absorb;U.damage.style.opacity=.35;setTimeout(()=>U.damage.style.opacity=0,90);if(P.hp<=0)end(false,'Suit failure. The field test was not contained.')}
function blocked(p){for(const q of solids)if(!q.door||!doorOpen)if(Math.abs(p.x-q.x)<q.a+P.r&&Math.abs(p.z-q.z)<q.c+P.r)return true;return false}
function move(dt){let x=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touch.l.x,z=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+touch.l.y,L=Math.hypot(x,z)||1;x/=L;z/=L;let sp=keys.has('ShiftLeft')||keys.has('ShiftRight')?6.2:4.25,f=V(-Math.sin(P.yaw),0,-Math.cos(P.yaw)),right=V(Math.cos(P.yaw),0,-Math.sin(P.yaw));P.v.x+=(f.x*(-z*sp)+right.x*(x*sp)-P.v.x)*Math.min(1,dt*10);P.v.z+=(f.z*(-z*sp)+right.z*(x*sp)-P.v.z)*Math.min(1,dt*10);P.v.y-=16*dt;if((keys.has('Space')||touch.jump)&&P.ground){P.v.y=6.2;P.ground=false;touch.jump=false}let q=P.p.clone();q.x+=P.v.x*dt;if(!blocked(q))P.p.x=q.x;else P.v.x=0;q=P.p.clone();q.z+=P.v.z*dt;if(!blocked(q))P.p.z=q.z;else P.v.z=0;P.p.y+=P.v.y*dt;if(P.p.y<1.72){P.p.y=1.72;P.v.y=0;P.ground=true}lamp.position.copy(P.p);if(mouse.lock){P.yaw-=mouse.dx*.0023;P.pitch=clamp(P.pitch-mouse.dy*.0023,-1.3,1.3);mouse.dx=mouse.dy=0}if(touch.rr.on){P.yaw-=touch.rr.x*.028;P.pitch=clamp(P.pitch-touch.rr.y*.022,-1.25,1.25)}cam.position.lerp(P.p,.95);cam.rotation.order='YXZ';cam.rotation.y=P.yaw;cam.rotation.x=P.pitch}
function shoot(){let g=guns[P.slot];if(P.cd||P.reload)return;if(P.mag[P.slot]<=0){reload();return}P.mag[P.slot]--;P.cd=g.rate;audio.beep(P.slot?150:210,.035,'square',.06);let o=cam.getWorldPosition(V()),d=cam.getWorldDirection(V()),flash=new THREE.Mesh(new THREE.SphereGeometry(.1,6,6),new THREE.MeshBasicMaterial({color:0xffd889}));flash.position.copy(o).addScaledVector(d,.55);W.add(flash);fx.push({o:flash,t:.05});for(const h of new THREE.Raycaster(o,d,0,g.range).intersectObjects(W.children,true)){let e=foes.find(q=>h.object.parent===q.g);if(e&&!e.dead){e.hp-=g.dmg;U.hit.style.opacity=1;setTimeout(()=>U.hit.style.opacity=0,70);if(e.hp<=0){e.dead=true;W.remove(e.g)}break}}}
function reload(){let g=guns[P.slot];if(!P.reload&&P.mag[P.slot]<g.max&&P.res[P.slot]){P.reload=1;audio.beep(120,.07,'sawtooth',.04)}}
function foesTick(dt){for(let e of foes)if(!e.dead){e.phase+=dt;e.cool-=dt;let to=P.p.clone().sub(e.g.position),d=to.length();if(d<20){to.y=0;to.normalize();e.g.position.addScaledVector(to,e.speed*dt);e.g.position.y=.8+.12*Math.sin(e.phase*4);e.g.lookAt(P.p.x,e.g.position.y,P.p.z);if(d<1.2)hurt(e.type==='spitter'?10:8);else if(d<13&&e.cool<=0){e.cool=e.type==='spitter'?1.5:1.9;let o=e.g.position.clone(),dir=P.p.clone().sub(o).normalize(),m=new THREE.Mesh(new THREE.SphereGeometry(.11,7,5),new THREE.MeshBasicMaterial({color:0xffb66f}));m.position.copy(o);W.add(m);fx.push({o:m,t:1.6,dir,shot:true})}}}}
function fxTick(dt){for(let i=fx.length-1;i>=0;i--){let e=fx[i];e.t-=dt;if(e.shot){e.o.position.addScaledVector(e.dir,10*dt);if(e.o.position.distanceTo(P.p)<.5){hurt(12);e.t=0}}if(e.t<=0){W.remove(e.o);fx.splice(i,1)}}}
function dropsTick(){for(let d of drops)if(!d.used){d.g.rotation.y+=.02;if(d.g.position.distanceTo(P.p)<1.2){d.used=true;W.remove(d.g);d.type==='med'?P.hp=clamp(P.hp+30,0,100):P.res[0]+=18;audio.beep(d.type==='med'?480:340,.08)}}}
function progression(dt){P.stageTime+=dt;let live=foes.filter(e=>!e.dead).length;if(P.stage===0&&P.p.z<10){P.stage=1;obj('Reach the lower test corridor.')}if(P.stage===1&&P.p.z<-5){P.stage=2;doorOpen=live<6;obj(live<6?'Containment breach detected. Push toward the reactor core.':'Clear the containment corridor to unlock the pressure door.')}if(P.stage===2&&P.p.z<-22&&P.stageTime<.2){alarm.intensity=5;obj('REACTOR EVENT // Survive the resonance pulse.');audio.beep(38,.35,'sawtooth',.08)}if(P.stage===2&&P.stageTime>5){P.stage=3;alarm.intensity=2.2;obj('Reach the loading bay. Something is moving outside.')}if(P.stage===3&&P.p.z<-45){P.stage=4;obj('Loading bay secure. Find the extraction route.')}if(P.stage===4&&P.p.z<-56){P.stage=5;doorOpen=true;obj('Extraction route unlocked. Reach the final door.')}if(P.stage===5&&P.p.z<-58)end(true,'The resonance event was contained and the facility survived the first field test.')}
function end(win,msg){state=win?'won':'lost';U.end.classList.remove('hidden');$('end-title').textContent=win?'TEST COMPLETE':'TEST FAILED';$('end-title').style.color=win?'#8be8ff':'#ff6670';$('end-copy').textContent=msg}
function use(){if(state==='playing'&&P.p.z>5){P.stage=1;obj('Initialization accepted. Move into the test corridor.');audio.beep(820,.1)}}
function hud(){U.hp.textContent=Math.ceil(P.hp);U.suit.textContent=Math.ceil(P.suit);let g=guns[P.slot];U.weapon.textContent=g.name+(P.reload?' // RELOADING':'');U.ammo.textContent=`${P.mag[P.slot]} / ${P.res[P.slot]}`;U.prompt.style.opacity=P.p.z>6?1:0;U.prompt.textContent=P.p.z>6?'E / TAP TO USE CONSOLE':'';U.sector.textContent=String(P.stage+1).padStart(2,'0')}
function controls(){addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Escape')state==='playing'?pause():resume();if(e.code==='KeyR')reload();if(e.code==='KeyE')use();if(e.code==='Digit1')P.slot=0;if(e.code==='Digit2')P.slot=1});addEventListener('keyup',e=>keys.delete(e.code));$('game').onclick=()=>state==='playing'&&$('game').requestPointerLock?.();document.addEventListener('pointerlockchange',()=>mouse.lock=document.pointerLockElement===$('game'));document.addEventListener('mousemove',e=>{if(mouse.lock){mouse.dx+=e.movementX;mouse.dy+=e.movementY}});document.addEventListener('mousedown',e=>e.button===0&&state==='playing'&&shoot());$('start-btn').onclick=()=>{audio.beep(440,.05);U.menu.classList.add('hidden');U.game.classList.remove('hidden');reset();if(innerWidth>800)$('game').requestPointerLock?.()};$('help-btn').onclick=()=>$('help-overlay').classList.remove('hidden');$('close-help').onclick=()=>$('help-overlay').classList.add('hidden');$('resume-btn').onclick=resume;$('restart-btn').onclick=()=>{U.end.classList.add('hidden');reset()};touchControls()}
function pause(){state='paused';U.pause.classList.remove('hidden');document.exitPointerLock?.()}function resume(){state='playing';U.pause.classList.add('hidden')}
function touchControls(){if(!('ontouchstart'in window))return;U.mobile.classList.remove('hidden');[['left-stick','l'],['right-stick','rr']].forEach(([id,s])=>{let el=$(id),pid=null;el.onpointerdown=e=>{pid=e.pointerId;el.setPointerCapture(pid);touch[s].on=true};el.onpointermove=e=>{if(e.pointerId!==pid)return;let q=el.getBoundingClientRect(),x=(e.clientX-q.left-q.width/2)/(q.width*.37),y=(e.clientY-q.top-q.height/2)/(q.height*.37);touch[s].x=clamp(x,-1,1);touch[s].y=clamp(y,-1,1)};const off=e=>{if(e.pointerId!==pid)return;touch[s].on=false;touch[s].x=touch[s].y=0;pid=null};el.onpointerup=off;el.onpointercancel=off});$('mobile-fire').onpointerdown=e=>{e.preventDefault();shoot()};$('mobile-jump').onpointerdown=e=>{e.preventDefault();touch.jump=true};$('mobile-reload').onpointerdown=e=>{e.preventDefault();reload()};$('mobile-use').onpointerdown=e=>{e.preventDefault();use()}}
controls();build();let boot=0,t=setInterval(()=>{boot++;U.fill.style.width=boot*20+'%';U.bt.textContent=['INITIALIZING RENDERER...','ALLOCATING TEST SECTOR...','BUILDING PROCEDURAL ASSETS...','VERIFYING INPUT SYSTEM...','READY.'][boot-1];if(boot===5){clearInterval(t);setTimeout(()=>{U.boot.remove();U.menu.classList.remove('hidden')},250)}},220);
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);let dt=Math.min(clock.getDelta(),.05);if(state==='playing'){now+=dt;P.cd=Math.max(0,P.cd-dt);if(P.reload>0){P.reload-=dt;if(P.reload<=0){let g=guns[P.slot],need=g.max-P.mag[P.slot],take=Math.min(need,P.res[P.slot]);P.mag[P.slot]+=take;P.res[P.slot]-=take;P.reload=0}}move(dt);foesTick(dt);fxTick(dt);dropsTick();progression(dt);hud()}r.render(scene,cam)}loop();addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();r.setSize(innerWidth,innerHeight);r.setPixelRatio(Math.min(devicePixelRatio,1.5))});