import * as THREE from 'three';import'./style.css';
const $=i=>document.getElementById(i),V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),C=(v,a,b)=>Math.max(a,Math.min(b,v));
const u={boot:$('boot'),menu:$('menu'),game:$('game-ui'),fill:$('boot-progress-fill'),text:$('boot-text'),obj:$('objective'),prompt:$('prompt'),hp:$('hp-value'),suit:$('suit-value'),sector:$('sector-value'),weapon:$('weapon-name'),ammo:$('ammo-value'),hit:$('hitmarker'),damage:$('damage-flash'),pause:$('pause-overlay'),end:$('end-overlay'),mobile:$('mobile-controls')};
const s=new THREE.Scene();s.background=new THREE.Color(0x04090d);s.fog=new THREE.FogExp2(0x081117,.024);const cam=new THREE.PerspectiveCamera(76,innerWidth/innerHeight,.05,140);
const ren=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});ren.setPixelRatio(Math.min(devicePixelRatio,1.5));ren.setSize(innerWidth,innerHeight);ren.outputColorSpace=THREE.SRGBColorSpace;ren.shadowMap.enabled=true;
s.add(new THREE.HemisphereLight(0x9ab9c8,0x081014,.62));let sun=new THREE.DirectionalLight(0xaad8e8,.7);sun.position.set(-14,22,10);sun.castShadow=true;s.add(sun);let alarm=new THREE.PointLight(0x66151d,2.2,16);alarm.position.set(0,3,-14);s.add(alarm);let lamp=new THREE.PointLight(0xcdefff,.8,7);s.add(lamp);
const W=new THREE.Group();s.add(W),sol=[],foes=[],drops=[],fx=[];const M={w:new THREE.MeshStandardMaterial({color:0x35454b,roughness:.88}),w2:new THREE.MeshStandardMaterial({color:0x59686c}),f:new THREE.MeshStandardMaterial({color:0x28363a,roughness:1}),d:new THREE.MeshStandardMaterial({color:0x121c20}),m:new THREE.MeshStandardMaterial({color:0x74868a,metalness:.7,roughness:.48}),g:new THREE.MeshStandardMaterial({color:0x2b8fab,transparent:true,opacity:.42}),a:new THREE.MeshStandardMaterial({color:0x5e7a55}),a2:new THREE.MeshStandardMaterial({color:0x23352a}),h:new THREE.MeshStandardMaterial({color:0xffc36c})};
const P={p:V(0,1.72,18),v:V(),yaw:Math.PI,pitch:0,hp:100,suit:100,ground:1,slot:0,mag:[12,4],res:[48,20],cd:0,reload:0,stage:0,st:0},G=[{n:'SIDEARM',max:12,rate:.16,d:24,r:42},{n:'PULSE CARBINE',max:4,rate:.48,d:48,r:32}],K=new Set(),mouse={lock:0,dx:0,dy:0},touch={l:{x:0,y:0,on:0},r:{x:0,y:0,on:0},jump:0};let state='boot',door=0;
const audio={c:null,beep(f,d,t='sine',g=.03){try{this.c??=new(window.AudioContext||window.webkitAudioContext)();this.c.resume();let o=this.c.createOscillator(),a=this.c.createGain();o.type=t;o.frequency.value=f;a.gain.value=g;o.connect(a).connect(this.c.destination);o.start();o.stop(this.c.currentTime+d)}catch{}}};
function box(x,y,z,a,b,c,m=M.w){let q=new THREE.Mesh(new THREE.BoxGeometry(a,b,c),m);q.position.set(x,y,z);q.receiveShadow=1;W.add(q)}function wall(x,z,a,c,d=0){sol.push({x,z,a:a/2,c:c/2,d})}
function room(z,w,d,h=5){box(0,0,z,w,.2,d,M.f);box(0,h,z,w,.2,d,M.d);box(-w/2,h/2,z,.3,h,d);box(w/2,h/2,z,.3,h,d);box(0,h/2,z-d/2,w,h,.3);box(0,h/2,z+d/2,w,h,.3);wall(-w/2,z,.3,d);wall(w/2,z,.3,d);wall(0,z-d/2,w,.3);wall(0,z+d/2,w,.3)}function cor(z,w=8,d=10){box(0,0,z,w,.2,d,M.f);box(0,5,z,w,.2,d,M.d);box(-w/2,2.5,z,.3,5,d,M.w2);box(w/2,2.5,z,.3,5,d,M.w2);wall(-w/2,z,.3,d);wall(w/2,z,.3,d)}
function light(z,c=0x7adff2){let l=new THREE.PointLight(c,2.5,8);l.position.set(-4.2,4.1,z);W.add(l);box(-4.2,4.1,z,1.6,.04,.08,new THREE.MeshBasicMaterial({color:c}))}
function foe(t,x,z){let g=new THREE.Group();g.position.set(x,.8,z);let b=new THREE.Mesh(new THREE.SphereGeometry(t==='spitter'?.58:.48,10,8),t==='spitter'?M.a:M.a2);b.scale.y=1.25;g.add(b);let e=new THREE.Mesh(new THREE.SphereGeometry(.16,8,6),new THREE.MeshBasicMaterial({color:t==='spitter'?0xffc36c:0xff4f5d}));e.position.set(0,.38,-.36);g.add(e);W.add(g);foes.push({g,t,h:t==='spitter'?70:44,c:Math.random(),sp:t==='spitter'?1.7:2.1,dead:0})}
function drop(t,x,z){let g=new THREE.Group();g.position.set(x,.72,z);g.add(new THREE.Mesh(t==='med'?new THREE.BoxGeometry(.42,.24,.72):new THREE.CylinderGeometry(.18,.18,.6,8),M.m));g.add(new THREE.PointLight(t==='med'?0x65ff8c:0xffbd62,1.2,3));W.add(g);drops.push({g,t,used:0})}
function build(){W.clear();sol.length=foes.length=drops.length=fx.length=0;room(16,12,16);cor(3);room(-7,14,10);cor(-17);room(-28,18,12,5.5);cor(-39,10);room(-50,22,16,6);[-20,-13,-3,13,20,-31,-46,-54].forEach(light);box(0,1.3,8,2.8,1.4,.7,M.m);box(0,2.5,-28,3.5,4.7,1.6,M.g);box(0,2.1,-16,4.5,4,.35,M.m);wall(0,-16,4.8,.8,true);drop('med',-2,14);drop('ammo',3,10);drop('ammo',-4,-6);drop('med',4,-30);drop('ammo',-5,-52);foe('runner',-3.6,-4);foe('runner',3.6,-7);foe('spitter',0,-12);foe('runner',-5,-31);foe('runner',5,-34);foe('spitter',0,-47);foe('runner',-5,-51);foe('runner',5,-53)}
function reset(){Object.assign(P,{p:V(0,1.72,18),v:V(),yaw:Math.PI,pitch:0,hp:100,suit:100,ground:1,slot:0,mag:[12,4],res:[48,20],cd:0,reload:0,stage:0,st:0});door=0;build();cam.position.copy(P.p);obj('Activate the initialization console.')}
function obj(t){u.obj.textContent=t}function damage(n){let x=Math.min(P.suit,n*.35);P.suit-=x;P.hp-=n-x;u.damage.style.opacity=.35;setTimeout(()=>u.damage.style.opacity=0,80);if(P.hp<=0)end(0,'Suit failure. The field test was not contained.')}
function blocked(p){return sol.some(q=>(!q.d||!door)&&Math.abs(p.x-q.x)<q.a+.32&&Math.abs(p.z-q.z)<q.c+.32)}
function move(dt){let x=(K.has('KeyD')?1:0)-(K.has('KeyA')?1:0)+touch.l.x,z=(K.has('KeyS')?1:0)-(K.has('KeyW')?1:0)+touch.l.y,L=Math.hypot(x,z)||1;x/=L;z/=L;let sp=K.has('ShiftLeft')?6.2:4.25,f=V(-Math.sin(P.yaw),0,-Math.cos(P.yaw)),rr=V(Math.cos(P.yaw),0,-Math.sin(P.yaw));P.v.x+=(f.x*-z*sp+rr.x*x*sp-P.v.x)*Math.min(1,dt*10);P.v.z+=(f.z*-z*sp+rr.z*x*sp-P.v.z)*Math.min(1,dt*10);P.v.y-=16*dt;if((K.has('Space')||touch.jump)&&P.ground)P.v.y=6.2,P.ground=0,touch.jump=0;let q=P.p.clone();q.x+=P.v.x*dt;if(!blocked(q))P.p.x=q.x;else P.v.x=0;q=P.p.clone();q.z+=P.v.z*dt;if(!blocked(q))P.p.z=q.z;else P.v.z=0;P.p.y+=P.v.y*dt;if(P.p.y<1.72)P.p.y=1.72,P.v.y=0,P.ground=1;lamp.position.copy(P.p);if(mouse.lock)P.yaw-=mouse.dx*.0023,P.pitch=C(P.pitch-mouse.dy*.0023,-1.3,1.3),mouse.dx=mouse.dy=0;if(touch.r.on)P.yaw-=touch.r.x*.028,P.pitch=C(P.pitch-touch.r.y*.022,-1.25,1.25);cam.position.lerp(P.p,.95);cam.rotation.order='YXZ';cam.rotation.y=P.yaw;cam.rotation.x=P.pitch}
function shoot(){let g=G[P.slot];if(P.cd||P.reload)return;if(P.mag[P.slot]<=0)return reload();P.mag[P.slot]--;P.cd=g.rate;audio.beep(P.slot?150:210,.035,'square',.06);let o=cam.getWorldPosition(V()),d=cam.getWorldDirection(V());for(const h of new THREE.Raycaster(o,d,0,g.r).intersectObjects(W.children,true)){let e=foes.find(q=>h.object.parent===q.g);if(e&&!e.dead){e.h-=g.d;e.h<=0&&(e.dead=1,W.remove(e.g));u.hit.style.opacity=1;setTimeout(()=>u.hit.style.opacity=0,70);break}}}
function reload(){let g=G[P.slot];if(!P.reload&&P.mag[P.slot]<g.max&&P.res[P.slot])P.reload=1}function foeTick(dt){for(let e of foes)if(!e.dead){e.cool-=dt;let d=P.p.distanceTo(e.g.position),t=P.p.clone().sub(e.g.position);if(d<20){t.y=0;t.normalize();e.g.position.addScaledVector(t,e.sp*dt);e.g.lookAt(P.p.x,.8,P.p.z);if(d<1.2)damage(e.t==='spitter'?10:8);else if(d<13&&e.cool<=0){e.cool=e.t==='spitter'?1.5:1.9;let m=new THREE.Mesh(new THREE.SphereGeometry(.1,6,5),new THREE.MeshBasicMaterial({color:0xffb66f}));m.position.copy(e.g.position);W.add(m);fx.push({o:m,t:1.4,d:t.clone().normalize(),shot:1})}}}}
function fxTick(dt){for(let i=fx.length-1;i>=0;i--){let e=fx[i];e.t-=dt;if(e.shot)e.o.position.addScaledVector(e.d,10*dt),e.o.position.distanceTo(P.p)<.5&&(damage(12),e.t=0);if(e.t<=0)W.remove(e.o),fx.splice(i,1)}}function dropsTick(){for(let d of drops)if(!d.used){d.g.rotation.y+=.02;if(d.g.position.distanceTo(P.p)<1.2){d.used=1;W.remove(d.g);d.t==='med'?P.hp=C(P.hp+30,0,100):P.res[0]+=18}}}
function progress(dt){P.st+=dt;let live=foes.filter(e=>!e.dead).length;if(P.stage===0&&P.p.z<10)P.stage=1,P.st=0,obj('Reach the lower test corridor.');if(P.stage===1&&P.p.z<-5)P.stage=2,P.st=0,door=live<6,obj(live<6?'Containment breach detected. Push toward the reactor core.':'Clear the containment corridor to unlock the pressure door.');if(P.stage===2&&P.p.z<-22&&P.st<.2)alarm.intensity=5,obj('REACTOR EVENT // Survive the resonance pulse.'),audio.beep(38,.35,'sawtooth',.08);if(P.stage===2&&P.st>5)P.stage=3,P.st=0,alarm.intensity=2.2,obj('Reach the loading bay. Something is moving outside.');if(P.stage===3&&P.p.z<-45)P.stage=4,P.st=0,obj('Loading bay secure. Find the extraction route.');if(P.stage===4&&P.p.z<-56)P.stage=5,P.st=0,door=1,obj('Extraction route unlocked. Reach the final door.');if(P.stage===5&&P.p.z<-58)end(1,'The resonance event was contained and the facility survived the first field test.')}
function end(win,msg){state=win?'won':'lost';u.end.classList.remove('hidden');$('end-title').textContent=win?'TEST COMPLETE':'TEST FAILED';$('end-title').style.color=win?'#8be8ff':'#ff6670';$('end-copy').textContent=msg}
function use(){if(state==='playing'&&P.p.z>5)P.stage=1,P.st=0,obj('Initialization accepted. Move into the test corridor.'),audio.beep(820,.1)}function hud(){let g=G[P.slot];u.hp.textContent=Math.ceil(P.hp);u.suit.textContent=Math.ceil(P.suit);u.weapon.textContent=g.n+(P.reload?' // RELOADING':'');u.ammo.textContent=`${P.mag[P.slot]} / ${P.res[P.slot]}`;u.prompt.style.opacity=P.p.z>6?1:0;u.prompt.textContent=P.p.z>6?'E / TAP TO USE CONSOLE':'';u.sector.textContent=String(P.stage+1).padStart(2,'0')}
function pause(){state='paused';u.pause.classList.remove('hidden');document.exitPointerLock?.()}function resume(){state='playing';u.pause.classList.add('hidden')}
function touchSetup(){if(!('ontouchstart'in window))return;u.mobile.classList.remove('hidden');for(const [id,n]of[['left-stick','l'],['right-stick','r']]){let e=$(id),idp=null;e.onpointerdown=x=>(idp=x.pointerId,e.setPointerCapture(idp),touch[n].on=1);e.onpointermove=x=>{if(x.pointerId!==idp)return;let q=e.getBoundingClientRect();touch[n].x=C((x.clientX-q.left-q.width/2)/(q.width*.37),-1,1);touch[n].y=C((x.clientY-q.top-q.height/2)/(q.height*.37),-1,1)};let off=x=>{if(x.pointerId===idp)touch[n].on=0,touch[n].x=touch[n].y=0,idp=null};e.onpointerup=off;e.onpointercancel=off}$('mobile-fire').onpointerdown=e=>{e.preventDefault();shoot()};$('mobile-jump').onpointerdown=e=>{e.preventDefault();touch.jump=1};$('mobile-reload').onpointerdown=e=>{e.preventDefault();reload()};$('mobile-use').onpointerdown=e=>{e.preventDefault();use()}}
addEventListener('keydown',e=>{K.add(e.code);if(e.code==='Escape')state==='playing'?pause():resume();if(e.code==='KeyR')reload();if(e.code==='KeyE')use();if(e.code==='Digit1')P.slot=0;if(e.code==='Digit2')P.slot=1});addEventListener('keyup',e=>K.delete(e.code));$('game').onclick=()=>state==='playing'&&$('game').requestPointerLock?.();document.addEventListener('pointerlockchange',()=>mouse.lock=document.pointerLockElement===$('game'));document.addEventListener('mousemove',e=>{if(mouse.lock)mouse.dx+=e.movementX,mouse.dy+=e.movementY});document.addEventListener('mousedown',e=>e.button===0&&state==='playing'&&shoot());$('start-btn').onclick=()=>{audio.beep(440,.05);u.menu.classList.add('hidden');u.game.classList.remove('hidden');reset();innerWidth>800&&$('game').requestPointerLock?.()};$('help-btn').onclick=()=>$('help-overlay').classList.remove('hidden');$('close-help').onclick=()=>$('help-overlay').classList.add('hidden');$('resume-btn').onclick=resume;$('restart-btn').onclick=()=>{u.end.classList.add('hidden');reset()};touchSetup();build();
let n=0,t=setInterval(()=>{n++;u.fill.style.width=n*20+'%';u.text.textContent=['INITIALIZING RENDERER...','ALLOCATING TEST SECTOR...','BUILDING PROCEDURAL ASSETS...','VERIFYING INPUT SYSTEM...','READY.'][n-1];if(n===5){clearInterval(t);u.boot.remove();u.menu.classList.remove('hidden')}},220);
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);let dt=Math.min(clock.getDelta(),.05);if(state==='playing'){P.cd=Math.max(0,P.cd-dt);if(P.reload>0&&(P.reload-=dt)<=0){let g=G[P.slot],x=Math.min(g.max-P.mag[P.slot],P.res[P.slot]);P.mag[P.slot]+=x;P.res[P.slot]-=x;P.reload=0}move(dt);foeTick(dt);fxTick(dt);dropsTick();progress(dt);hud()}ren.render(s,cam)}loop();addEventListener('resize',()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();ren.setSize(innerWidth,innerHeight);ren.setPixelRatio(Math.min(devicePixelRatio,1.5))});